version: '3.8'
services:
  api:
    image: todo-service:latest
    container_name: 'todo_api'
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=GolangTodo
      - DB_PORT=5432
      - TEST_DB_NAME=GolangTodo
      - PORT=8000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    container_name: 'go-docker_db'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=GolangTodo
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
