definitions:
  controllers.body:
    properties:
      body:
        type: string
      status:
        type: boolean
      title:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.ToDo:
    properties:
      body:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      status:
        type: boolean
      title:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /todo:
    get:
      consumes:
      - application/json
      description: Получение списка todo, опционально можно отфильтровать по статусу
      parameters:
      - description: Filter by status
        in: query
        name: status
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: List of todos
          schema:
            items:
              $ref: '#/definitions/models.ToDo'
            type: array
        "500":
          description: Internal server error
          schema:
            type: string
      summary: List todos
      tags:
      - todos
    post:
      consumes:
      - application/json
      description: |-
        Создание нового todo
        title должен быть не короче 3
      parameters:
      - description: Create Todo
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/controllers.body'
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created
          schema:
            $ref: '#/definitions/models.ToDo'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new todo
      tags:
      - todos
  /todo/{id}:
    delete:
      consumes:
      - application/json
      description: Удаление todo по id
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: Successfully deleted
          schema:
            type: string
        "404":
          description: Todo not found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a todo
      tags:
      - todos
    get:
      consumes:
      - application/json
      description: Получение todo по id
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Todo details
          schema:
            $ref: '#/definitions/models.ToDo'
        "404":
          description: Todo not found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Show a todo
      tags:
      - todos
    put:
      consumes:
      - application/json
      description: Обновление todo по id
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Todo
        in: body
        name: todo
        schema:
          $ref: '#/definitions/controllers.body'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated
          schema:
            $ref: '#/definitions/models.ToDo'
        "404":
          description: Todo not found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a todo
      tags:
      - todos
swagger: "2.0"
